### ISSUE TITLE
improve test runner

### ISSUE THREAD

**Issue by aladdin-add** [kataw/kataw#7]
feat:

- [x] exit code
- [x] test coverage (with c8)
- [ ] parsing/printer/linter/minify options

refactor:

- [ ] get rid of the constants and make a .md template
- [x] separately update snapshots

bugfix:

- [ ] non-ascii chars and escaped chars get correctly printed in .md files

**Comment by KFlash** [comment]
@aladdin-add The printer options need to cover

- parser options

- printer options

- linter options

- minify options

For the printer options you can read the readme in the `compiler/printer` folder. 

Regarding the liner - just take a look at ESLint options (*my next TODO*).

**Comment by aladdin-add** [comment]
it seems just as the same as parsing: input + options => output.

what else need to be done in the test runner?

**Comment by aladdin-add** [comment]
I didn't see `compiler/printer`: https://github.com/kataw/kataw/tree/b21950e59484f0ee4da87ff9ab942fea219ed386/src/compiler

did you forget to push? v(ノへ￣、)

**Comment by KFlash** [comment]
Here is the [printer options](https://github.com/kataw/kataw/tree/main/src/compiler/printer)

**Comment by KFlash** [comment]
test runner? the `lib/` folder. Should modularize everything, and the `autogenerate.ts` complains if the `gen`folder doesn't exist before you try to auto generate.

The  `generateOutputBlock` in `run.ts`  is a temporary hack. It should be modularized to get content from a  ` .md` file with placeholders instead of using the constants we are using now.

Also consider to make a own CLI for the runner, and extract the options at top of  `generateOutputBlock`  in it's own  `.md`  file. Rollup have a plugin for this I think, and you can look into their source too see how they do this.

And general cleanup

**Comment by aladdin-add** [comment]
fine, I'll look into it.

**Comment by KFlash** [comment]
Off topic. I'm soon to push the printer to a private repo so we can play around with  it there and fix bugs before pushing to main repo. It's a complex piece of code, but I'm getting there.

While waiting for that you can see [the test files}(https://github.com/kataw/kataw/tree/printer/test/__snapshot__/printer) for the printer too get a hin of how the pretty printing will be

**Comment by aladdin-add** [comment]
updated the op.

we can make a few PRs to the address these issues, what do you think merging #8 now?

**Comment by KFlash** [comment]
Maybe merge [this](https://github.com/kataw/WIP-printer/blob/main/test/run.ts#L45-L60) and [this](https://github.com/kataw/WIP-printer/blob/main/test/run.ts#L181-L196)  changes first?

**Comment by KFlash** [comment]
@aladdin-add Any progress on this? We also need to add a option to switch the printer comments on / off so we can test it correctly.

**Comment by aladdin-add** [comment]
got some rl stuff. but I will try to get it in 3~4 days.

**Comment by KFlash** [comment]
same thing here. Rl problems. Take your time :)

**Comment by KFlash** [comment]
this can be closed?
