### ISSUE TITLE
confusing typings

### ISSUE THREAD

**Issue by aladdin-add** [kataw/kataw#75]
https://github.com/kataw/kataw/blob/48e2b10ac80e9b3acb91946ae205855153d25628/src/forEachChild.ts#L14-L21

what's the type of "node" -- `SyntaxKind` is just numbers, `node.kind/node.flags` will throw an error?

**Comment by KFlash** [comment]
Everything is just a number ;) I guess the type of node should be `SyntaxKind` because punctuators and keywords are `childLess`. If not then node could be either `SyntaxKind | TokenSyntaxKind` or  only `TokenSyntaxKind` if keyword / punctuator tokens.

What do you mean with `node.kind/node.flags will throw an error?`.   A `node.kind` is equal to `node.type` in ESTree, but in Kataw just a number ;)

`node.flags` hold the `NodeFlags` enums and all info related to each CST node packed as an series of numbers due to per and CST size.  See the `Public API` on how to extract this kind of info.

**Comment by aladdin-add** [comment]
if `node` is a number, `node.kind` is always `undef`.

```js
var node = 0;
node.kind; // => undefined
```

**Comment by KFlash** [comment]
In your example you create a new `node` and set the value to `0`. It does not contain the `kind` property.

They all extends `SyntaxNode` so use that one.

See this CST node for hints

https://github.com/kataw/kataw/blob/main/src/ast/expressions/class-element.ts

**Comment by aladdin-add** [comment]
maybe it should be `node: SyntaxNode`, not `node: SyntaxKind `

**Comment by KFlash** [comment]
Looks correct, but do not try to walk `token` and `keyword` tokens. Because this is internal and you want to gain perf, you can do this

```ts
if (node.flags & NodeFlags.ChildLess) { 
console.log('Aladdin-add do not walk this node!");
}

// Keep walking!
```

**Comment by KFlash** [comment]
In short you can either do `node.kind & ....` or  `node.flags & ....` to extract the same information you would need 200 - 300 code lines to write in ESLint.

**Comment by KFlash** [comment]
@aladdin-add Is this solved?

**Comment by KFlash** [comment]
@aladdin-add should we close this?

**Comment by aladdin-add** [comment]
haven't got time for this. but let's keep it open to help not lost track of it?

**Comment by KFlash** [comment]
sure. when do you think you get time to test the walker?

**Comment by KFlash** [comment]
close this?

**Comment by aladdin-add** [comment]
there is still a TODO: update any to the correct typing.

**Comment by aladdin-add** [comment]
closing as fixed.
